v2.0.0: migrate to ESP-IDF v5.5.0, update architecture, and fix bugs

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,4 +1,9 @@
-image: python:latest
+image: espressif/idf:v5.5
+
+workflow:
+  rules:
+    - if: '($CI_PIPELINE_SOURCE == "merge_request_event") && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop")'
+    - if: '$CI_COMMIT_TAG'
 
 stages:
   - setup
@@ -11,20 +16,15 @@ stages:
 cache:
   paths:
     - .oi/
+    - build/
 
 setup:
   stage: setup
   script:
-    - curl -fsSL -o get-platformio.py https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py
-    - python3 get-platformio.py
-    - /root/.platformio/penv/bin/pio pkg update  
     - rm -rf .oi/
     - mkdir -p .oi/bin/oi-firmware-$(cat version.txt)
     - mkdir -p .oi/docs/
     - mkdir -p .oi/lib/
-  rules:
-    - if: '($CI_PIPELINE_SOURCE == "merge_request_event") && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || "develop")'
-    - if: '$CI_COMMIT_TAG'
   tags:
     - oi-firmware
 
@@ -32,93 +32,47 @@ setup:
   stage: build:bin
   needs:
     - job: setup
+  script:
+    - cp sdkconfig.ci.defaults.${MODULE_TYPE,,} sdkconfig
+    - idf.py reconfigure
+    - idf.py build
   after_script:
-    - cp .pio/build/${PIOENV}/firmware.bin .oi/bin/oi-firmware-$(cat version.txt)/${PIOENV}_firmware-$(cat version.txt).bin
-    - cp .pio/build/${PIOENV}/ota_data_initial.bin .oi/bin/oi-firmware-$(cat version.txt)/${PIOENV}_ota_data_initial-$(cat version.txt).bin
-    - cp .pio/build/${PIOENV}/bootloader.bin .oi/bin/oi-firmware-$(cat version.txt)/${PIOENV}_bootloader-$(cat version.txt).bin
-    - cp .pio/build/${PIOENV}/partitions.bin .oi/bin/oi-firmware-$(cat version.txt)/${PIOENV}_partitions-$(cat version.txt).bin
-  rules:
-    - if: '($CI_PIPELINE_SOURCE == "merge_request_event") && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || "develop")'
-    - if: '$CI_COMMIT_TAG'
+    - cp build/OI-Firmware.bin .oi/bin/oi-firmware-$(cat version.txt)/${MODULE_TYPE,,}_firmware-$(cat version.txt).bin
+    - cp build/ota_data_initial.bin .oi/bin/oi-firmware-$(cat version.txt)/${MODULE_TYPE,,}_ota_data_initial-$(cat version.txt).bin
+    - cp build/bootloader/bootloader.bin .oi/bin/oi-firmware-$(cat version.txt)/${MODULE_TYPE,,}_bootloader-$(cat version.txt).bin
+    - cp build/partition_table/partition-table.bin .oi/bin/oi-firmware-$(cat version.txt)/${MODULE_TYPE,,}_partitions-$(cat version.txt).bin
   tags:
     - oi-firmware
 
 build:bin:core:
   extends: .build:bin
-  script:
-    - /root/.platformio/penv/bin/pio run -e core
   variables:
-    PIOENV: "core"
+    MODULE_TYPE: "OI_CORE"
 
 build:bin:discrete:
   extends: .build:bin
-  script:
-    - /root/.platformio/penv/bin/pio run -e discrete
   variables:
-    PIOENV: "discrete"
-
-# build:bin:discreteve:
-#   extends: .build:bin
-#   script:
-#     - /root/.platformio/penv/bin/pio run -e discreteve
-#   variables:
-#     PIOENV: "discreteve"
+    MODULE_TYPE: "OI_DISCRETE"
 
 build:bin:stepper:
   extends: .build:bin
-  script:
-    - /root/.platformio/penv/bin/pio run -e stepper
   variables:
-    PIOENV: "stepper"
-
-# build:bin:stepperve:
-#   extends: .build:bin
-#   script:
-#     - /root/.platformio/penv/bin/pio run -e stepperve
-#   variables:
-#     PIOENV: "stepperve"
+    MODULE_TYPE: "OI_STEPPER"
 
 build:bin:mixed:
   extends: .build:bin
-  script:
-    - /root/.platformio/penv/bin/pio run -e mixed
   variables:
-    PIOENV: "mixed"
+    MODULE_TYPE: "OI_MIXED"
 
 build:bin:relayhp:
   extends: .build:bin
-  script:
-    - /root/.platformio/penv/bin/pio run -e relayhp
   variables:
-    PIOENV: "relayhp"
+    MODULE_TYPE: "OI_RELAY_HP"
 
 build:bin:relaylp:
   extends: .build:bin
-  script:
-    - /root/.platformio/penv/bin/pio run -e relaylp
   variables:
-    PIOENV: "relaylp"
-
-# build:bin:brushless:
-#   extends: .build:bin
-#   script:
-#     - /root/.platformio/penv/bin/pio run -e brushless
-#   variables:
-#     PIOENV: "brushless"
-
-build:bin:analogls:
-  extends: .build:bin
-  script:
-    - /root/.platformio/penv/bin/pio run -e analogls
-  variables:
-    PIOENV: "analogls"
-
-build:bin:dc:
-  extends: .build:bin
-  script:
-    - /root/.platformio/penv/bin/pio run -e dc
-  variables:
-    PIOENV: "dc"
+    MODULE_TYPE: "OI_RELAY_LP"
 
 build:examples:
   stage: build:examples
@@ -126,16 +80,15 @@ build:examples:
     - job: setup
   script:
     - |
-      find examples/ -name "*.cpp" | while read -r f; do
+      find components/openindus/examples/ -name "*.cpp" | while read -r f; do
         echo "Build $f"
-        cat $f > main/main.cpp
-        /root/.platformio/penv/bin/pio run -e core || { echo "Error: Build failed for $f"; exit 1; }
+        cp $f main/main.cpp
+        cp sdkconfig.ci.defaults.oi_core sdkconfig
+        idf.py reconfigure
+        idf.py build || { echo "Error: Build failed for $f"; exit 1; }
       done
   after_script:
     - git restore main/main.cpp
-  rules:
-    - if: '($CI_PIPELINE_SOURCE == "merge_request_event") && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || "develop")'
-    - if: '$CI_COMMIT_TAG'
   tags:
     - oi-firmware
 
@@ -155,9 +108,6 @@ build:docs:
     - cd ..
   after_script:
     - cp -r docs/build/html/ .oi/docs/
-  rules:
-    - if: '($CI_PIPELINE_SOURCE == "merge_request_event") && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || "develop")'
-    - if: '$CI_COMMIT_TAG'
   tags:
     - oi-firmware
 
@@ -165,21 +115,17 @@ build:docs:examples:
   stage: build:docs
   needs:
     - job: setup
-  before_script:
-    - /root/.platformio/penv/bin/pio pkg install --library "felis/USB-Host-Shield-20@^1.6.0"
-    - /root/.platformio/penv/bin/pio pkg install --library "paulstoffregen/Ethernet@^2.0.0"
   script:
     - |
       find docs/examples/ -name "*.cpp" | while read -r f; do
         echo "Build $f"
-        cat $f > main/main.cpp
-        /root/.platformio/penv/bin/pio run -e core || { echo "Error: Build failed for $f"; exit 1; }
+        cp $f main/main.cpp
+        cp sdkconfig.ci.defaults.oi_core sdkconfig
+        idf.py reconfigure
+        idf.py build || { echo "Error: Build failed for $f"; exit 1; }
       done
   after_script:
     - git restore main/main.cpp
-  rules:
-    - if: '($CI_PIPELINE_SOURCE == "merge_request_event") && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || "develop")'
-    - if: '$CI_COMMIT_TAG'
   tags:
     - oi-firmware
 
@@ -188,7 +134,8 @@ pkg:library:
   needs:
     - job: setup
   script:
-    - /root/.platformio/penv/bin/pio pkg pack --output=".oi/lib/"
+    - tar -czf .oi/lib/openindus-$(cat version.txt).tar.gz components/openindus/
+    - tar -czf .oi/lib/arduino-esp32-$(cat version.txt).tar.gz components/arduino/
   rules:
     - if: '$CI_COMMIT_TAG'
   tags:
@@ -199,15 +146,10 @@ deploy:bin:
   needs:
     - job: build:bin:core
     - job: build:bin:discrete
-    # - job: build:bin:discreteve
     - job: build:bin:stepper
-    # - job: build:bin:stepperve
     - job: build:bin:mixed
     - job: build:bin:relayhp
     - job: build:bin:relaylp
-    # - job: build:bin:brushless
-    - job: build:bin:analogls
-    - job: build:bin:dc
   before_script:
     - apt update
     - apt install -y lftp
